import type { Claim } from "@/types";
import { aggregate, SUB_SCORE_DEFS } from "./scoring";

function subs(values: Record<keyof typeof SUB_SCORE_DEFS, number>) {
  return (Object.keys(SUB_SCORE_DEFS) as Array<keyof typeof SUB_SCORE_DEFS>).map(
    (k) => ({
      key: k,
      label: SUB_SCORE_DEFS[k].label,
      description: SUB_SCORE_DEFS[k].description,
      weight: SUB_SCORE_DEFS[k].weight,
      value: values[k],
    }),
  );
}

const WATER_SUBS = subs({
  photo_completeness: 64,
  moisture_documentation: 82,
  drying_log_quality: 55,
  estimate_evidence_match: 71,
  equipment_justification: 60,
  room_consistency: 78,
  timeline_consistency: 70,
  supplement_readiness: 68,
  adjuster_risk: 62,
  documentation_strength: 80,
});

const MOLD_SUBS = subs({
  photo_completeness: 70,
  moisture_documentation: 60,
  drying_log_quality: 65,
  estimate_evidence_match: 58,
  equipment_justification: 55,
  room_consistency: 72,
  timeline_consistency: 58,
  supplement_readiness: 50,
  adjuster_risk: 48,
  documentation_strength: 62,
});

const ROOF_SUBS = subs({
  photo_completeness: 88,
  moisture_documentation: 95,
  drying_log_quality: 95,
  estimate_evidence_match: 80,
  equipment_justification: 90,
  room_consistency: 84,
  timeline_consistency: 86,
  supplement_readiness: 75,
  adjuster_risk: 78,
  documentation_strength: 80,
});

export const CLAIMS: Claim[] = [
  {
    id: "C-2026-00148",
    number: "C-2026-00148",
    org_id: "org_demo",
    type: "water",
    cat: 2,
    status: "needs-review",
    policyholder: "Robert & Diane Mendez",
    address: "4421 Magnolia Ln, Houston, TX 77019",
    loss_date: "2026-04-28",
    cause_of_loss: "Supply line failure under kitchen sink",
    carrier: "State Farm",
    adjuster_name: "Karen Whitaker",
    claim_number_carrier: "SF-89C-441-7723",
    rcv: 11420,
    acv: 10180,
    created_at: "2026-04-29T13:21:00Z",
    updated_at: "2026-05-11T09:14:00Z",
    score: aggregate(WATER_SUBS),
    sub_scores: WATER_SUBS,
    narrative_draft:
      "On April 28, 2026, the property at 4421 Magnolia Ln experienced a Category 2 water loss originating from a failed supply line under the kitchen sink. Mitigation crews arrived within 4 hours, performed extraction across affected areas, set drying equipment, and began daily psychrometric monitoring per IICRC S500. Affected rooms include Kitchen, Dining, Living Room (LR1), and Hallway. Drying equipment included 8 air movers and 2 LGR dehumidifiers, adjusted across 4 days based on daily moisture readings. Antimicrobial application was performed in affected areas where Category 2 water contact occurred. See attached moisture log, drying log, sketch and photos.",
    files: [
      {
        id: "f1",
        name: "Xactimate-Estimate-Mendez.pdf",
        category: "estimate",
        size_kb: 412,
        uploaded_at: "2026-04-29T13:25:00Z",
        uploaded_by: "Dave (Estimator)",
        parse_status: "parsed",
      },
      {
        id: "f2",
        name: "Insurance-Estimate-StateFarm.pdf",
        category: "insurance_estimate",
        size_kb: 380,
        uploaded_at: "2026-05-04T10:11:00Z",
        uploaded_by: "Lauren (Admin)",
        parse_status: "parsed",
      },
      {
        id: "f3",
        name: "Photos-CompanyCam-Day1.zip",
        category: "photo",
        size_kb: 18420,
        uploaded_at: "2026-04-29T16:02:00Z",
        uploaded_by: "Tony (Mit Mgr)",
        parse_status: "parsed",
        tags: ["wet-drywall", "extraction", "moisture-meter"],
      },
      {
        id: "f4",
        name: "Moisture-Log-Day1-Day2.csv",
        category: "moisture_log",
        size_kb: 24,
        uploaded_at: "2026-04-30T20:40:00Z",
        uploaded_by: "Tony (Mit Mgr)",
        parse_status: "parsed",
      },
      {
        id: "f5",
        name: "Moisture-Log-Day4.csv",
        category: "moisture_log",
        size_kb: 18,
        uploaded_at: "2026-05-02T19:35:00Z",
        uploaded_by: "Tony (Mit Mgr)",
        parse_status: "parsed",
      },
      {
        id: "f6",
        name: "Drying-Log-Days-1-4.pdf",
        category: "drying_log",
        size_kb: 68,
        uploaded_at: "2026-05-03T07:55:00Z",
        uploaded_by: "Tony (Mit Mgr)",
        parse_status: "parsed",
      },
      {
        id: "f7",
        name: "Sketch-Mendez-Floorplan.pdf",
        category: "sketch",
        size_kb: 95,
        uploaded_at: "2026-04-29T14:00:00Z",
        uploaded_by: "Dave (Estimator)",
        parse_status: "parsed",
      },
      {
        id: "f8",
        name: "Work-Authorization-Signed.pdf",
        category: "authorization",
        size_kb: 142,
        uploaded_at: "2026-04-29T13:35:00Z",
        uploaded_by: "Lauren (Admin)",
        parse_status: "parsed",
      },
      {
        id: "f9",
        name: "Adjuster-Email-Intro.pdf",
        category: "correspondence",
        size_kb: 22,
        uploaded_at: "2026-05-01T08:14:00Z",
        uploaded_by: "Lauren (Admin)",
        parse_status: "parsed",
      },
    ],
    line_items: [
      {
        id: "li1",
        source: "contractor",
        code: "WTR DRY 2",
        description: "Remove drywall — flood cut 2 ft",
        room: "Living Room (LR1)",
        quantity: 24,
        unit: "LF",
        unit_price: 3.85,
        total: 92.4,
        evidence_found: ["3 photos w/ measuring tape", "Sketch annotated"],
        evidence_missing: [],
        risk: "low",
        confidence: 94,
      },
      {
        id: "li2",
        source: "contractor",
        code: "WTR EQP AM",
        description: "Air mover (per day) × 4 × 4 days",
        room: "Master Bath",
        quantity: 16,
        unit: "DAY",
        unit_price: 27.5,
        total: 440,
        evidence_found: ["Day 1, 2 drying logs", "Placement photo Day 1"],
        evidence_missing: ["Day 3, Day 4 drying log entries", "Justification for 4 AMs in 48 sqft"],
        risk: "medium",
        confidence: 81,
        recommended_action:
          "Upload Day 3+4 drying logs and add F9 note justifying 4 AMs (Class 3 conditions)",
      },
      {
        id: "li3",
        source: "contractor",
        code: "WTR ANTM",
        description: "Antimicrobial treatment",
        room: "Kitchen + Dining + LR1 + Hallway",
        quantity: 950,
        unit: "SF",
        unit_price: 0.42,
        total: 399,
        evidence_found: ["1 photo of spray bottle"],
        evidence_missing: [
          "Per-room application photos",
          "SDS sheet",
          "Sqft mismatch with sketch (sketch = 720 SF)",
        ],
        risk: "high",
        confidence: 88,
        recommended_action:
          "Re-measure or correct quantity; add 1 application photo per room and SDS upload",
      },
      {
        id: "li4",
        source: "contractor",
        code: "WTR EXT WT",
        description: "Water extraction — light",
        room: "Kitchen",
        quantity: 180,
        unit: "SF",
        unit_price: 0.62,
        total: 111.6,
        evidence_found: ["Photo of extraction wand", "Wet-to-dry zone photo"],
        evidence_missing: [],
        risk: "low",
        confidence: 92,
      },
      {
        id: "li5",
        source: "contractor",
        code: "WTR EQP DH",
        description: "Dehumidifier (LGR) per day × 2 × 4 days",
        room: "Whole Floor",
        quantity: 8,
        unit: "DAY",
        unit_price: 78.5,
        total: 628,
        evidence_found: ["Day 1, 2 drying logs", "Equipment placement photos"],
        evidence_missing: ["Day 3 reading"],
        risk: "medium",
        confidence: 79,
      },
      {
        id: "li6",
        source: "contractor",
        code: "R&R DRY 1/2",
        description: "Drywall replace — 1/2 in",
        room: "Living Room (LR1)",
        quantity: 48,
        unit: "SF",
        unit_price: 2.95,
        total: 141.6,
        evidence_found: ["Demo photo"],
        evidence_missing: ["After-photo with measure"],
        risk: "medium",
        confidence: 70,
      },
      {
        id: "li7",
        source: "contractor",
        code: "WTR CNT",
        description: "Containment / poly barrier",
        room: "Hallway → LR1",
        quantity: 240,
        unit: "SF",
        unit_price: 0.85,
        total: 204,
        evidence_found: [],
        evidence_missing: [
          "Containment photo before/after",
          "Hours documented",
        ],
        risk: "high",
        confidence: 86,
        recommended_action:
          "Upload at least 1 containment-in-place photo and 1 removal photo",
      },
    ],
    moisture: [
      { id: "m1", day: 1, date: "2026-04-29", room: "LR1", material: "Drywall", reading_pct: 38.4, equipment: "BD-2100" },
      { id: "m2", day: 1, date: "2026-04-29", room: "Kitchen", material: "Subfloor", reading_pct: 28.1, equipment: "BD-2100" },
      { id: "m3", day: 2, date: "2026-04-30", room: "LR1", material: "Drywall", reading_pct: 28.5, equipment: "BD-2100" },
      { id: "m4", day: 2, date: "2026-04-30", room: "Kitchen", material: "Subfloor", reading_pct: 22.9, equipment: "BD-2100" },
      { id: "m5", day: 4, date: "2026-05-02", room: "LR1", material: "Drywall", reading_pct: 14.2, equipment: "BD-2100" },
      { id: "m6", day: 4, date: "2026-05-02", room: "Kitchen", material: "Subfloor", reading_pct: 13.5, equipment: "BD-2100" },
    ],
    drying: [
      { id: "d1", day: 1, date: "2026-04-29", equipment: ["4× AM", "2× LGR"], temp_f: 76, rh_pct: 58, gpp: 86, status: "ok" },
      { id: "d2", day: 2, date: "2026-04-30", equipment: ["4× AM", "2× LGR"], temp_f: 78, rh_pct: 49, gpp: 70, status: "ok" },
      { id: "d3", day: 3, date: "2026-05-01", equipment: [], temp_f: 0, rh_pct: 0, gpp: 0, status: "missing", notes: "No log entry uploaded" },
      { id: "d4", day: 4, date: "2026-05-02", equipment: ["4× AM", "2× LGR"], temp_f: 79, rh_pct: 41, gpp: 56, status: "ok" },
    ],
    missing: [
      { id: "mr1", key: "drying_log_day3", label: "Day 3 drying log", category: "log", status: "open", assignee: "Tony", severity: "critical", due_at: "2026-05-12" },
      { id: "mr2", key: "flood_cut_after_photo", label: "Flood-cut after-photo with measuring tape (LR1)", category: "photo", status: "open", assignee: "Field Tech", severity: "medium", due_at: "2026-05-13" },
      { id: "mr3", key: "antimicrobial_app_photos", label: "Antimicrobial application photos per room", category: "photo", status: "open", assignee: "Field Tech", severity: "high", due_at: "2026-05-13" },
      { id: "mr4", key: "antimicrobial_sds", label: "Antimicrobial product SDS", category: "doc", status: "open", assignee: "Tony", severity: "low" },
      { id: "mr5", key: "containment_photo", label: "Containment in place / removal photos", category: "photo", status: "open", assignee: "Field Tech", severity: "high" },
      { id: "mr6", key: "source_of_loss_photo", label: "Source-of-loss photo (failed supply line)", category: "photo", status: "open", assignee: "Tony", severity: "medium" },
      { id: "mr7", key: "iicrc_cert", label: "IICRC WRT certification on file", category: "doc", status: "satisfied", severity: "low" },
    ],
    questions: [
      { id: "q1", question: "Please provide the drying log for Day 3.", rationale: "No psychrometric reading was logged on May 1.", pre_answer_hint: "Upload Day 3 log; if no entry exists, add a written explanation and visit notes.", severity: "high" },
      { id: "q2", question: "Justify 4 air movers in 48 sqft master bath.", rationale: "S500 guidance suggests 1–2 AMs for that footprint.", pre_answer_hint: "Add F9 note: Class 3 conditions, full saturation of vanity wall, drying timeline.", severity: "medium", related_line_item_id: "li2" },
      { id: "q3", question: "Confirm antimicrobial coverage area.", rationale: "Estimate shows 950 SF, sketch shows 720 SF affected.", pre_answer_hint: "Reconcile sketch and estimate; correct quantity or add additional area photos.", severity: "high", related_line_item_id: "li3" },
      { id: "q4", question: "Provide source-of-loss photo.", rationale: "Cause-of-loss photo not located in upload set.", pre_answer_hint: "Upload photo of failed supply line.", severity: "medium" },
      { id: "q5", question: "Provide containment documentation.", rationale: "Containment line item present, no photos.", pre_answer_hint: "Add 2 photos (in place / removal).", severity: "medium" },
      { id: "q6", question: "Confirm dry standard achieved.", rationale: "Day 4 readings strong but no completion certificate.", pre_answer_hint: "Generate completion certificate referencing Day 4 readings.", severity: "low" },
      { id: "q7", question: "Why was extraction not billed in LR1?", rationale: "Photos show standing water in LR1 but no extraction line item there.", pre_answer_hint: "Either add extraction line item or note pre-existing wet condition.", severity: "low" },
    ],
    findings: [
      { id: "fnd1", type: "log_gap", severity: "critical", confidence: 96, message: "Day 3 drying log missing.", evidence_refs: ["d3"], suggested_action: "Upload missing Day 3 log or written justification." },
      { id: "fnd2", type: "equipment_overuse", severity: "medium", confidence: 78, message: "4 air movers in 48 sqft master bath exceeds typical S500 guidance.", evidence_refs: ["li2"], related_line_item_id: "li2", suggested_action: "Add justification note (Class 3, full wall saturation)." },
      { id: "fnd3", type: "inconsistency", severity: "high", confidence: 88, message: "Antimicrobial 950 SF vs floor plan 720 SF.", evidence_refs: ["li3", "f7"], related_line_item_id: "li3", suggested_action: "Reconcile to sketch or document additional area." },
      { id: "fnd4", type: "missing_doc", severity: "high", confidence: 92, message: "Containment line item billed without supporting photos.", evidence_refs: ["li7"], suggested_action: "Upload containment in-place / removal photos." },
      { id: "fnd5", type: "weak_evidence", severity: "medium", confidence: 84, message: "Flood-cut line item lacks after-photo with measurement.", evidence_refs: ["li1"], suggested_action: "Re-photo with tape measure visible." },
      { id: "fnd6", type: "missing_doc", severity: "medium", confidence: 90, message: "No source-of-loss photo uploaded.", evidence_refs: [], suggested_action: "Upload photo of failed supply line." },
    ],
    tasks: [
      { id: "t1", title: "Upload Day 3 drying log", assignee: "Tony", status: "open", priority: "high", due_at: "2026-05-12", related_finding_id: "fnd1" },
      { id: "t2", title: "Re-photo flood cut LR1 with tape measure", assignee: "Field Tech", status: "open", priority: "med", due_at: "2026-05-13", related_finding_id: "fnd5" },
      { id: "t3", title: "Justify 4 AMs in MBath (F9 note)", assignee: "Dave (Estimator)", status: "in_progress", priority: "med", related_finding_id: "fnd2" },
      { id: "t4", title: "Reconcile antimicrobial 950 vs 720 SF", assignee: "Dave (Estimator)", status: "open", priority: "high", related_finding_id: "fnd3" },
      { id: "t5", title: "Upload containment photos (in-place + removal)", assignee: "Field Tech", status: "open", priority: "high", related_finding_id: "fnd4" },
      { id: "t6", title: "Upload source-of-loss photo", assignee: "Tony", status: "open", priority: "med", related_finding_id: "fnd6" },
      { id: "t7", title: "Add SDS for antimicrobial product", assignee: "Tony", status: "open", priority: "low" },
    ],
    reports: [
      { id: "r1", kind: "claim_qa", generated_at: "2026-05-09T18:30:00Z", generated_by: "Dave (Estimator)", whitelabel: false },
    ],
  },
  {
    id: "C-2026-00161",
    number: "C-2026-00161",
    org_id: "org_demo",
    type: "mold",
    status: "needs-review",
    policyholder: "Helen Park",
    address: "881 Caldera St, Tampa, FL 33611",
    loss_date: "2026-04-09",
    cause_of_loss: "Long-term moisture intrusion behind shower wall",
    carrier: "Citizens",
    adjuster_name: "Marcus Lee",
    claim_number_carrier: "CIT-2026-114-883",
    rcv: 8420,
    acv: 7390,
    created_at: "2026-04-12T11:01:00Z",
    updated_at: "2026-05-10T15:32:00Z",
    score: aggregate(MOLD_SUBS),
    sub_scores: MOLD_SUBS,
    narrative_draft:
      "Helen Park's primary bathroom presented visible microbial growth behind the shower wall consistent with long-term moisture intrusion. Per IICRC S520, containment was established, HEPA vacuuming and antimicrobial treatment performed, and removal of affected porous materials completed. Pre-remediation air sample collected. Post-remediation clearance pending.",
    files: [
      { id: "mf1", name: "Pre-Remediation-Inspection.pdf", category: "estimate", size_kb: 280, uploaded_at: "2026-04-12T11:30:00Z", uploaded_by: "Tony", parse_status: "parsed" },
      { id: "mf2", name: "Containment-Photos.zip", category: "photo", size_kb: 7400, uploaded_at: "2026-04-13T17:11:00Z", uploaded_by: "Field Tech", parse_status: "parsed" },
      { id: "mf3", name: "Air-Sample-Pre.pdf", category: "other", size_kb: 320, uploaded_at: "2026-04-13T08:55:00Z", uploaded_by: "Tony", parse_status: "parsed" },
      { id: "mf4", name: "Scope-of-Work.pdf", category: "estimate", size_kb: 210, uploaded_at: "2026-04-12T11:35:00Z", uploaded_by: "Dave", parse_status: "parsed" },
    ],
    line_items: [
      { id: "ml1", source: "contractor", code: "MLD CNT 6", description: "Containment — 6 mil poly", room: "MBath", quantity: 120, unit: "SF", unit_price: 1.15, total: 138, evidence_found: ["Containment photos"], evidence_missing: ["Negative pressure verification"], risk: "medium", confidence: 80 },
      { id: "ml2", source: "contractor", code: "MLD HEPA", description: "HEPA air scrubber per day × 3 days", room: "MBath", quantity: 3, unit: "DAY", unit_price: 89, total: 267, evidence_found: ["Equipment photo Day 1"], evidence_missing: ["Hour meter readings", "Day 2-3 confirmation"], risk: "medium", confidence: 76 },
      { id: "ml3", source: "contractor", code: "MLD ANTM", description: "Antimicrobial application", room: "MBath", quantity: 220, unit: "SF", unit_price: 0.45, total: 99, evidence_found: [], evidence_missing: ["Application photo", "SDS sheet"], risk: "high", confidence: 88, recommended_action: "Upload at least 1 application photo + product SDS" },
      { id: "ml4", source: "contractor", code: "MLD R&R", description: "Drywall removal & disposal", room: "MBath", quantity: 80, unit: "SF", unit_price: 3.6, total: 288, evidence_found: ["Demo photos"], evidence_missing: [], risk: "low", confidence: 92 },
      { id: "ml5", source: "contractor", code: "MLD CLR", description: "Post-remediation clearance test", room: "MBath", quantity: 1, unit: "EA", unit_price: 425, total: 425, evidence_found: [], evidence_missing: ["Clearance lab report"], risk: "critical", confidence: 95, recommended_action: "Schedule clearance with 3rd-party IEP and upload report before submission" },
    ],
    moisture: [],
    drying: [],
    missing: [
      { id: "mlm1", key: "post_clearance", label: "Post-remediation clearance air sample", category: "doc", status: "open", assignee: "Tony", severity: "critical" },
      { id: "mlm2", key: "ppe_photos", label: "Technician PPE photos", category: "photo", status: "open", assignee: "Field Tech", severity: "medium" },
      { id: "mlm3", key: "containment_integrity", label: "Containment integrity verification (negative pressure log)", category: "doc", status: "open", assignee: "Tony", severity: "medium" },
      { id: "mlm4", key: "antm_sds", label: "Antimicrobial SDS sheet", category: "doc", status: "open", assignee: "Tony", severity: "low" },
      { id: "mlm5", key: "hepa_runtime", label: "HEPA scrubber runtime / hour meter", category: "log", status: "open", assignee: "Field Tech", severity: "medium" },
    ],
    questions: [
      { id: "mlq1", question: "Provide post-remediation clearance test results.", rationale: "S520 requires post-clearance for billed remediation scope.", pre_answer_hint: "Schedule and upload IEP clearance report.", severity: "critical" },
      { id: "mlq2", question: "Provide PPE compliance photos.", rationale: "Insurance often verifies S520 compliance via PPE imagery.", pre_answer_hint: "Upload 1 photo per technician with PPE.", severity: "medium" },
      { id: "mlq3", question: "Provide HEPA scrubber runtime.", rationale: "3 day billing without meter readings.", pre_answer_hint: "Upload meter photos or written confirmation.", severity: "medium" },
    ],
    findings: [
      { id: "mfn1", type: "missing_doc", severity: "critical", confidence: 96, message: "No post-remediation clearance test on file.", evidence_refs: ["ml5"], suggested_action: "Do not submit prior to clearance upload." },
      { id: "mfn2", type: "missing_doc", severity: "medium", confidence: 84, message: "PPE photos not uploaded.", evidence_refs: [], suggested_action: "Upload PPE photos." },
      { id: "mfn3", type: "weak_evidence", severity: "high", confidence: 88, message: "Antimicrobial billed without application evidence.", evidence_refs: ["ml3"], suggested_action: "Add application photo and SDS." },
    ],
    tasks: [
      { id: "mlt1", title: "Schedule post-remediation clearance test", assignee: "Tony", status: "open", priority: "high", related_finding_id: "mfn1" },
      { id: "mlt2", title: "Upload PPE compliance photos", assignee: "Field Tech", status: "open", priority: "med", related_finding_id: "mfn2" },
      { id: "mlt3", title: "Upload antimicrobial SDS + application photo", assignee: "Tony", status: "open", priority: "med", related_finding_id: "mfn3" },
    ],
    reports: [],
  },
  {
    id: "C-2026-00177",
    number: "C-2026-00177",
    org_id: "org_demo",
    type: "roof",
    status: "submission-ready",
    policyholder: "Greg Tilman",
    address: "212 Hawkridge Dr, Atlanta, GA 30342",
    loss_date: "2026-04-02",
    cause_of_loss: "Hail event — NOAA confirmed 1.5 in hail",
    carrier: "Allstate",
    adjuster_name: "Beth Cordova",
    claim_number_carrier: "ALL-77123-RCS",
    rcv: 13180,
    acv: 11460,
    created_at: "2026-04-05T09:01:00Z",
    updated_at: "2026-05-10T11:21:00Z",
    score: aggregate(ROOF_SUBS),
    sub_scores: ROOF_SUBS,
    narrative_draft:
      "Property at 212 Hawkridge Dr sustained hail damage during the April 2, 2026 storm event (NOAA confirmed 1.5 in hail). Roof inspection performed on April 4 documented hail strikes across all elevations, including 3 test squares (front, back, left). Damage observed on shingles, ridge cap, vent boots, and drip edge. ITEL submitted for shingle match. Contractor scope reflects full replacement per state matching statute.",
    files: [
      { id: "rf1", name: "Adjuster-Estimate-Allstate.pdf", category: "insurance_estimate", size_kb: 410, uploaded_at: "2026-04-08T10:05:00Z", uploaded_by: "Lauren", parse_status: "parsed" },
      { id: "rf2", name: "Contractor-Estimate-Tilman.pdf", category: "estimate", size_kb: 480, uploaded_at: "2026-04-09T08:14:00Z", uploaded_by: "Dave", parse_status: "parsed" },
      { id: "rf3", name: "Roof-Photos-CompanyCam.zip", category: "photo", size_kb: 22100, uploaded_at: "2026-04-04T18:24:00Z", uploaded_by: "Field Tech", parse_status: "parsed" },
      { id: "rf4", name: "Drone-Footage.mp4", category: "video", size_kb: 64200, uploaded_at: "2026-04-04T19:01:00Z", uploaded_by: "Field Tech", parse_status: "parsed" },
      { id: "rf5", name: "NOAA-Storm-Report.pdf", category: "other", size_kb: 240, uploaded_at: "2026-04-08T09:55:00Z", uploaded_by: "Dave", parse_status: "parsed" },
    ],
    line_items: [
      { id: "rl1", source: "contractor", code: "RFG R&R 25", description: "Tear off / R&R 3-tab shingles 25 yr", room: "Roof — Front", quantity: 18.4, unit: "SQ", unit_price: 285, total: 5244, evidence_found: ["Tear-off photos", "Test squares"], evidence_missing: [], risk: "low", confidence: 94 },
      { id: "rl2", source: "contractor", code: "RFG DRIP", description: "R&R Drip edge", room: "Roof — Perimeter", quantity: 184, unit: "LF", unit_price: 2.85, total: 524.4, evidence_found: ["Tear-off photos showing drip edge"], evidence_missing: [], risk: "low", confidence: 92 },
      { id: "rl3", source: "contractor", code: "RFG UNDR", description: "Synthetic underlayment", room: "Roof — Whole", quantity: 18.4, unit: "SQ", unit_price: 48, total: 883, evidence_found: ["Photos of existing underlayment"], evidence_missing: [], risk: "low", confidence: 90 },
      { id: "rl4", source: "contractor", code: "RFG VNT", description: "R&R turbine / pipe vents", room: "Roof — Back", quantity: 4, unit: "EA", unit_price: 88, total: 352, evidence_found: [], evidence_missing: ["Closeup photos of damaged vents"], risk: "medium", confidence: 76, recommended_action: "Upload closeup photos of each damaged vent" },
      { id: "rl5", source: "contractor", code: "RFG ITEL", description: "ITEL match request", room: "Roof — Whole", quantity: 1, unit: "EA", unit_price: 95, total: 95, evidence_found: ["ITEL request submitted"], evidence_missing: ["ITEL response"], risk: "medium", confidence: 80 },
    ],
    moisture: [],
    drying: [],
    missing: [
      { id: "rm1", key: "vent_closeups", label: "Closeup photos of damaged vents", category: "photo", status: "open", assignee: "Field Tech", severity: "medium" },
      { id: "rm2", key: "itel_response", label: "ITEL match response", category: "doc", status: "open", assignee: "Lauren", severity: "medium" },
    ],
    questions: [
      { id: "rq1", question: "Provide ITEL match response.", rationale: "Required for shingle match line item.", pre_answer_hint: "Forward ITEL response when received.", severity: "medium" },
      { id: "rq2", question: "Provide closeup photos of damaged vents.", rationale: "Item billed without photo evidence.", pre_answer_hint: "Upload closeups.", severity: "medium" },
      { id: "rq3", question: "Confirm matching statute applicability.", rationale: "Adjuster scope shows partial replacement.", pre_answer_hint: "Reference Georgia matching guidance with citation.", severity: "low" },
    ],
    findings: [
      { id: "rfn1", type: "supplement_candidate", severity: "medium", confidence: 84, message: "Underlayment line missing in adjuster estimate.", evidence_refs: ["rl3"], suggested_action: "Submit supplement with synthetic underlayment line." },
      { id: "rfn2", type: "supplement_candidate", severity: "medium", confidence: 80, message: "Drip edge missing from adjuster scope.", evidence_refs: ["rl2"], suggested_action: "Submit supplement with drip edge line + photo." },
      { id: "rfn3", type: "weak_evidence", severity: "medium", confidence: 78, message: "Damaged vents billed without closeup photos.", evidence_refs: ["rl4"], suggested_action: "Upload vent closeups." },
      { id: "rfn4", type: "missing_doc", severity: "medium", confidence: 75, message: "ITEL match response not yet uploaded.", evidence_refs: ["rl5"], suggested_action: "Upload ITEL response when received." },
    ],
    tasks: [
      { id: "rt1", title: "Upload closeup vent photos", assignee: "Field Tech", status: "open", priority: "med", related_finding_id: "rfn3" },
      { id: "rt2", title: "Forward ITEL response", assignee: "Lauren", status: "open", priority: "med", related_finding_id: "rfn4" },
      { id: "rt3", title: "Draft supplement: underlayment + drip edge", assignee: "Dave", status: "in_progress", priority: "high", related_finding_id: "rfn1" },
    ],
    reports: [
      { id: "rr1", kind: "supplement_readiness", generated_at: "2026-05-08T15:21:00Z", generated_by: "Dave", whitelabel: false },
    ],
  },
];

export function getClaim(id: string): Claim | undefined {
  return CLAIMS.find((c) => c.id === id || c.number === id);
}
