import { notFound } from "next/navigation";
import { FileText, Download, AlertTriangle, ListChecks, FileSpreadsheet, MessageSquare, UserCheck } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getClaimById as getClaim } from "@/lib/store";
import { formatDate } from "@/lib/utils";

const REPORT_TYPES = [
  {
    kind: "claim_qa",
    title: "Claim QA Report",
    desc: "Full QA summary: score, sub-scores, top findings, recommended actions.",
    icon: FileText,
    audience: "Internal — Owner & Estimator",
  },
  {
    kind: "missing_docs",
    title: "Missing Documentation Report",
    desc: "Checklist of missing items grouped by assignee, with due dates.",
    icon: ListChecks,
    audience: "Internal — Admin & Field",
  },
  {
    kind: "adjuster_risk",
    title: "Adjuster Risk Report",
    desc: "Forecasted adjuster questions with pre-answers from your evidence.",
    icon: AlertTriangle,
    audience: "Internal — Estimator",
  },
  {
    kind: "supplement_readiness",
    title: "Supplement Readiness Report",
    desc: "Field-documented items missing from the estimate with evidence pointers.",
    icon: FileSpreadsheet,
    audience: "Internal — Estimator",
  },
  {
    kind: "estimator_notes",
    title: "Internal Estimator Notes",
    desc: "Per-line-item notes, evidence sources and suggested Xactimate F9 entries.",
    icon: MessageSquare,
    audience: "Internal — Estimator",
  },
  {
    kind: "customer_summary",
    title: "Customer / Adjuster-Friendly Summary",
    desc: "Neutral, non-antagonistic overview suitable for external sharing.",
    icon: UserCheck,
    audience: "External — Optional",
  },
] as const;

export default async function ReportsTab({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const claim = getClaim(id);
  if (!claim) notFound();

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-[15px] font-semibold">Reports</h2>
        <p className="text-[12px] text-app-muted">
          Six purpose-built report types. Pro and Enterprise plans support
          white-label branding.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2">
        {REPORT_TYPES.map((r) => {
          const implemented =
            r.kind === "claim_qa" ||
            r.kind === "missing_docs" ||
            r.kind === "adjuster_risk";
          return (
            <Card key={r.kind} className="p-5">
              <div className="flex items-start justify-between gap-3">
                <div className="grid h-10 w-10 place-items-center rounded-lg bg-brand-50 text-brand">
                  <r.icon className="h-5 w-5" />
                </div>
                <Badge tone="muted">{r.audience}</Badge>
              </div>
              <h3 className="mt-4 text-[15px] font-semibold">{r.title}</h3>
              <p className="mt-1 text-[13px] text-app-muted">{r.desc}</p>
              <div className="mt-4 flex gap-2">
                {implemented ? (
                  <a
                    href={`/api/claims/${claim.id}/reports/${r.kind}`}
                    target="_blank"
                    rel="noreferrer"
                  >
                    <Button size="sm" className="gap-1.5">
                      <Download className="h-3.5 w-3.5" /> Download PDF
                    </Button>
                  </a>
                ) : (
                  <Button size="sm" disabled className="gap-1.5">
                    <Download className="h-3.5 w-3.5" /> Coming in v1.1
                  </Button>
                )}
              </div>
            </Card>
          );
        })}
      </div>

      {claim.reports.length > 0 && (
        <Card>
          <div className="border-b border-app-border p-5">
            <h3 className="text-[14px] font-semibold">Recently generated</h3>
          </div>
          <ul className="divide-y divide-app-border">
            {claim.reports.map((r) => (
              <li key={r.id} className="flex items-center gap-3 px-5 py-3">
                <FileText className="h-4 w-4 text-brand" />
                <div className="flex-1">
                  <div className="text-[13px] font-medium">
                    {REPORT_TYPES.find((t) => t.kind === r.kind)?.title ?? r.kind}
                  </div>
                  <div className="text-[11px] text-app-muted">
                    Generated by {r.generated_by} · {formatDate(r.generated_at)}
                  </div>
                </div>
                <Button variant="outline" size="sm" className="gap-1.5">
                  <Download className="h-3.5 w-3.5" /> Download
                </Button>
              </li>
            ))}
          </ul>
        </Card>
      )}
    </div>
  );
}
