import Link from "next/link";
import { FileText, Download } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { listClaims } from "@/lib/store";
import { formatDate } from "@/lib/utils";

export const dynamic = "force-dynamic";

const LABEL = {
  claim_qa: "Claim QA Report",
  missing_docs: "Missing Documentation",
  adjuster_risk: "Adjuster Risk Report",
  supplement_readiness: "Supplement Readiness",
  estimator_notes: "Internal Estimator Notes",
  customer_summary: "Customer / Adjuster Summary",
} as const;

export default function GlobalReportsPage() {
  const CLAIMS = listClaims();
  const reports = CLAIMS.flatMap((c) =>
    c.reports.map((r) => ({ ...r, claim: c })),
  );

  return (
    <div className="container-page py-8">
      <h1 className="text-2xl font-bold tracking-tight">Reports</h1>
      <p className="text-[13px] text-app-muted">
        All generated reports across your organization.
      </p>

      <Card className="mt-6">
        {reports.length === 0 ? (
          <div className="p-12 text-center">
            <FileText className="mx-auto h-8 w-8 text-app-muted" />
            <h3 className="mt-2 text-[15px] font-semibold">No reports yet</h3>
            <p className="mt-1 text-[12px] text-app-muted">
              Generate your first report from a claim detail page.
            </p>
          </div>
        ) : (
          <ul className="divide-y divide-app-border">
            {reports.map((r) => (
              <li key={r.id} className="flex items-center gap-4 px-5 py-4">
                <FileText className="h-5 w-5 text-brand" />
                <div className="min-w-0 flex-1">
                  <div className="text-[14px] font-medium">{LABEL[r.kind]}</div>
                  <div className="text-[11px] text-app-muted">
                    <Link
                      href={`/app/claims/${r.claim.id}`}
                      className="hover:text-brand"
                    >
                      {r.claim.policyholder}
                    </Link>{" "}
                    · Generated by {r.generated_by} · {formatDate(r.generated_at)}
                  </div>
                </div>
                {r.whitelabel && <Badge tone="info">White-label</Badge>}
                <Button variant="outline" size="sm" className="gap-1.5">
                  <Download className="h-3.5 w-3.5" /> Download
                </Button>
              </li>
            ))}
          </ul>
        )}
      </Card>
    </div>
  );
}
